# Generated by Django 6.0.7 on 2026-08-13 21:22

import apps.clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(max_length=18, unique=True, validators=[apps.clientes.models.validar_cpf_cnpj]),
        ),
    ]
