# Generated by Django 6.0.7 on 2026-10-01 21:49

import apps.rh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofuncionario',
            name='arquivo',
            field=models.FileField(storage=apps.rh.models.armazenamento_privado, upload_to='rh/documentos/'),
        ),
    ]
